SET(zlib_LIB_DEPENDS "")
SET(utils_LIB DEPENDS "")
SET(znzlib_LIB_DEPENDS  "zlib;")
SET(niftiio_LIB_DEPENDS  "")
SET(fslio_LIB_DEPENDS "niftiio;znz;zlib;")
SET(newmat_LIB_DEPENDS "")
SET(newran_LIB_DEPENDS "")
SET(libpng_LIB_DEPENDS "")
SET(miscmaths_LIB_DEPENDS "newmat;newran;")
SET(newimage_LIB_DEPENDS "miscmaths;fslio;")
SET(libpng_LIB_DEPENDS "zlib;")